GameOfLife.Mvc/Controllers/UserGameController.cs
using GameOfLife.Business;
using GameOfLife.Data;
using GameOfLife.Mvc.Contracts;
using GameOfLife.Mvc.Models;
using GameOfLife.Mvc.Services;
using System;
using System.Linq;
using System.Web.Mvc;

namespace GameOfLife.Mvc.Controllers
{
    public class UserGameController : BaseController
    {
        #region Members

        private IActiveGameService _service;

        #endregion

        #region Ctors

        public UserGameController(IActiveGameService service)
        {
            _service = service;
        }

        public UserGameController() : this(new ActiveGameService())
        {
        }

        #endregion

        #region Actions

        #region Anonymous

        public ActionResult Index()
        {
            var games = _service.ActiveGames.Select(g => new GameViewModel(g)).ToList();
            var model = new GameListViewModel()
            {
                Games = games
            };
            return View("Games", model);
        }

        public ActionResult CreateGame(int templateId = -1)
        {
            var model = new GameViewModel();
            using (var unit = new UnitOfWork(GOLContext.Create()))
                model.UserTemplates = unit.UserTemplates.GetAll().ToList();
            model.UserTemplateId = templateId;
            return View("Create", model);
        }

        public ActionResult MakeActive(int id)
        {
            using (var unit = new UnitOfWork(GOLContext.Create()))
            {
                var game = unit.UserGames.Get(id);
                if (game == null)
                {
                    ErrorMessage = "Unable to find game";
                    return RedirectToAction("Saved");
                }
                var model = new GameViewModel(game);
                return AddToActiveAndRedirect(model);
            }
        }

        [HttpPost]
        public ActionResult Create(GameViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var uow = new UnitOfWork(GOLContext.Create()))
                    {
                        // Get template and insert into model
                        var template = uow.UserTemplates.Get(model.UserTemplateId);
                        model.InsertTemplateIntoGame(template);
                    }

                    return AddToActiveAndRedirect(model);
                }
            }
            catch (Exception ex)
            {
                // Something happened when trying to create the game
                ErrorMessage = $"Invalid game. Message: {ex.Message}";
            }
            // Just return the create view
            return View("Create", model);
        }

        public ActionResult PlayGame(string gameName)
        {
            var game = _service.ActiveGames.SingleOrDefault(g => g.Name == gameName);
            if (game == null)
            {
                ErrorMessage = $"Unable to find game by name: {gameName}";
                RedirectToAction("Index");
            }

            var model = new GameViewModel(game);
            return View("Play", model);
        }

        public ActionResult GetUpdatedGameCells(string gameName)
        {
            // Get game
            var game = _service.ActiveGames.SingleOrDefault(g => g.Name == gameName);
            if (game == null)
                return Json(new { CellsForDisplay = "Error" }, JsonRequestBehavior.AllowGet);

            // Tick it over and save it back to session
            game.Tick();
            _service.AddOrUpdateActiveGame(game);

            // Return model for display
            var model = new GameViewModel(game);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DeleteActiveGame(string gameName)
        {
            _service.DeleteGame(gameName);
            return RedirectToAction("Index");
        }

        #endregion

        #region Authorised

        [Authorize]
        public ActionResult Saved()
        {
            using (var unit = new UnitOfWork(GOLContext.Create()))
            {
                var games = unit.UserGames.GetAll()
                    .Where(g => g.UserId == ApplicationUser.Id)
                    .Select(g => new GameViewModel(g))
                    .ToList();
                var model = new GameListViewModel()
                {
                    Games = games
                };
                return View("Saved", model);
            }
        }

        [Authorize]
        public ActionResult SaveGame(string gameName)
        {
            // Get game
            var game = _service.ActiveGames.SingleOrDefault(g => g.Name == gameName);
            if (game == null)
            {
                ErrorMessage = $"Unable to find game by name: {gameName}";
                RedirectToAction("Index");
            }

            // Persist to db as saved game
            game.UserId = ApplicationUser.Id;
            using (var unit = new UnitOfWork(GOLContext.Create()))
            {
                unit.UserGames.AddOrUpdate(game);
                unit.Complete();
                SuccessMessage = "Game Saved";
            }

            // Show play view
            return View("Play", new GameViewModel(game));
        }

        [Authorize]
        public ActionResult DeleteSavedGame(int id)
        {
            using (var unit = new UnitOfWork(GOLContext.Create()))
            {
                var game = unit.UserGames.Get(id);
                if (game != null)
                {
                    // Check that user has permissions to delete
                    if (game.UserId != ApplicationUser.Id && !User.IsInRole(RoleKeys.ADMIN))
                    {
                        ErrorMessage = "You cannot delete a game that isn't yours";
                        var games = unit.UserGames.GetAll()
                                                  .Where(g => g.UserId == ApplicationUser.Id)
                                                  .Select(g => new GameViewModel(g))
                                                  .ToList();
                        var model = new GameListViewModel()
                        {
                            Games = games
                        };
                        return View("Saved", model);
                    }
                    else
                    {
                        // Game exists and user authorised
                        unit.UserGames.Remove(game);
                        unit.Complete();
                        SuccessMessage = "Game Deleted";
                    }
                }
            }
            return RedirectToAction("Saved");
        }

        #endregion

        #endregion

        #region Helpers

        private RedirectToRouteResult AddToActiveAndRedirect(GameViewModel model)
        {
            // Since we are using the name to find games, ensure unique
            if (_service.ActiveGames.Any(g => g.Name == model.Name))
                model.Name += "2";

            // Add current game state to session and display play game view
            _service.AddOrUpdateActiveGame(model.CurrentUserGameState);
            return RedirectToAction("PlayGame", new { gameName = model.Name });
        }

        #endregion
    }
}

GameOfLife.Mvc/Controllers/UserTemplateController.cs
using GameOfLife.Data;
using GameOfLife.Mvc.Models;
using System.Linq;
using System.Web.Mvc;

namespace GameOfLife.Mvc.Controllers
{
    /// <summary>
    /// Responsible for all UserTemplate Interactions
    /// </summary>
    public class UserTemplateController : BaseController
    {
        #region Actions

        #region Anonymous

        public ActionResult Index(bool userOnly = false)
        {
            using (var uow = new UnitOfWork(GOLContext.Create()))
            {
                var templateModels = uow.UserTemplates.GetAll()
                                                      .Select(t => new TemplateViewModel(t))
                                                      .ToList();
                var model = new TemplatesListViewModel(templateModels);
                return View("Templates", model);
            }
        }

        public ActionResult Details(int id)
        {
            using (var uow = new UnitOfWork(GOLContext.Create()))
            {
                // Try get model
                var template = uow.UserTemplates.SingleOrDefault(t => t.Id == id);
                if (template == null)
                {
                    // If we could not find the template, redirect
                    ErrorMessage = "Oops... Unable to find template.";
                    var templates = uow.UserTemplates.GetAll().Select(t => new TemplateViewModel(t)).ToList();
                    return View("Templates", new TemplatesListViewModel(templates));
                }
                return View("Details", new TemplateViewModel(template));
            }
        }

        [HttpPost]
        public ActionResult Search(TemplatesListViewModel model)
        {
            using (var uow = new UnitOfWork(GOLContext.Create()))
            {
                // Get filtered list of templates
                model.Templates = uow.UserTemplates.Find(t => t.Name.ToUpper().Contains(model.Filter.ToUpper()))
                    .Select(t => new TemplateViewModel(t))
                    .ToList();
                return View("Templates", model);
            }
        }

        #endregion

        #region Authorised

        [Authorize]
        public ActionResult MyTemplates()
        {
            using (var uow = new UnitOfWork(GOLContext.Create()))
            {
                var templateModels = uow.UserTemplates.GetAll()
                                                      .Where(t => t.UserId == ApplicationUser.Id)
                                                      .Select(t => new TemplateViewModel(t))
                                                      .ToList();
                var model = new TemplatesListViewModel(templateModels);
                return View("UserTemplates", model);
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult SearchMyTemplates(TemplatesListViewModel model)
        {
            using (var uow = new UnitOfWork(GOLContext.Create()))
            {
                // Get filtered list of templates
                model.Templates = uow.UserTemplates.GetAll()
                                                   .Where(t => t.UserId == User.ToApplicationUser().Id && t.Name.ToUpper().Contains(model.Filter.ToUpper()))
                                                   .Select(t => new TemplateViewModel(t))
                                                   .ToList();
                return View("UserTemplates", model);
            }
        }

        [Authorize]
        public ActionResult Edit(int? id)
        {
            using (var uow = new UnitOfWork(GOLContext.Create()))
            {
                // Try get template and populate model
                var template = uow.UserTemplates.SingleOrDefault(t => t.Id == id);

                TemplateViewModel model;
                if (template == null)
                {
                    model = new TemplateViewModel(ApplicationUser?.Id);
                }
                else
                {
                    // Make sure that user is authorised
                    if (template.UserId != ApplicationUser.Id && !User.IsInRole(RoleKeys.ADMIN))
                    {
                        ErrorMessage = "That was naughty! You are not allowed to edit that template";
                        var templates = uow.UserTemplates.GetAll()
                                                         .Select(t => new TemplateViewModel(t)).ToList();
                        return View("Templates", new TemplatesListViewModel(templates));
                    }

                    // User is authorised
                    model = new TemplateViewModel(template);
                }

                return View("Edit", model);
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(TemplateViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Check for errors
                string error = string.Empty;
                if (!model.IsValid)
                    error = "Invalid template. Please make sure that the cells match your specified width and height";

                if (!string.IsNullOrEmpty(error))
                {
                    // Last error wins
                    ErrorMessage = error;
                    return View("Edit", model);
                }

                // Persist
                using (var uow = new UnitOfWork(GOLContext.Create()))
                {
                    // Try Retrieve
                    var template = uow.UserTemplates.SingleOrDefault(t => t.Id == model.Id);
                    if (template == null)
                    {
                        // Does not exit so lets just add it
                        template = model.UserTemplate;
                        template.UserId = ApplicationUser?.Id;
                    }
                    else
                    {
                        // It's an update, so update the object already in tracking
                        template.Name = model.Name;
                        template.Height = model.Height;
                        template.Width = model.Width;
                        template.Cells = model.Cells;
                        template.UserId = ApplicationUser?.Id;
                    }
                    uow.UserTemplates.AddOrUpdate(template);
                    uow.Complete();
                    SuccessMessage = $"Template {template.Name} successfully saved";
                }
            }
            return View("Edit", model);
        }

        [Authorize]
        public ActionResult Delete(int id)
        {
            using (var uow = new UnitOfWork(GOLContext.Create()))
            {
                // Try get model
                var template = uow.UserTemplates.SingleOrDefault(t => t.Id == id);
                if (template == null)
                {
                    // If we could not find the template, redirect
                    ErrorMessage = "Oops... Unable to find template.";
                    var templates = uow.UserTemplates.GetAll().Select(t => new TemplateViewModel(t)).ToList();
                    return View("Templates", new TemplatesListViewModel(templates));
                }

                var model = new TemplateViewModel(template);
                model.DeleteTemplate();

                return RedirectToAction("Index", true);
            }
        }

        #endregion

        #endregion
    }
}

GameOfLife.Mvc/Views/UserTemplate/Details.cshtml
@using GameOfLife.Data;
@model GameOfLife.Mvc.Models.TemplateViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cells)
        </dt>

        <dd>
            <pre style="display:inline-block;">
                @Html.DisplayFor(model => model.CellsForDisplay)
            </pre>
        </dd>
    </dl>
</div>
<p>
    @{
        if (User != null)
        {
            var appUser = User.ToApplicationUser();
            if (appUser != null)
            {
                if (Model.UserId == appUser.Id || User.IsInRole(RoleKeys.ADMIN))
                {
                    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
                }
            }
        }
    }
    @Html.ActionLink("Create Active Game", "CreateGame", "UserGame", new { templateId = Model.Id }, new { @class = "btn btn-default" })
    @Html.ActionLink("Back to All Templates", "Index", "UserTemplate", null, new { @class = "btn btn-default" })
    @Html.ActionLink("Back to My Templates", "MyTemplates", "UserTemplate", null, new { @class = "btn btn-default" })
</p>

GameOfLife.Mvc/Views/UserTemplate/Edit.cshtml
@model GameOfLife.Mvc.Models.TemplateViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit/Add Template</h2>

@using (Html.BeginForm("Edit", "UserTemplate"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TemplateViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cells, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Cells, new { @class = "form-control", placeholder = "'0' is alive and 'X' is dead...", rows = 10 })
                @Html.ValidationMessageFor(model => model.Cells, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
                @if (Model.Id != -1)
                {
                @Html.ActionLink("Delete", "Delete", new { id = Model.Id }, new { @class = "btn btn-default" })
                }
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

GameOfLife.Mvc/Views/UserTemplate/Templates.cshtml
@using GameOfLife.Data
@model GameOfLife.Mvc.Models.TemplatesListViewModel

@{
    ViewBag.Title = "Templates";

    var appUser = User.ToApplicationUser();
}

<h2>Templates</h2>

<p>
    @Html.ActionLink("Create New", "Edit", null, new { @class = "btn btn-primary" })
</p>

@using (Html.BeginForm("Search", "UserTemplate"))
{
    @Html.EditorFor(m => m.Filter, new { @class = "form-control" })
    <input type="submit" class="btn btn-primary" value="Search" />
    @Html.ActionLink("Clear", "Index", "UserTemplate", null, new { @class = "btn" })
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].Width)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].Cells)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].CreateBy)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model.Templates)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                <pre style="display:inline-block;">
                    @Html.DisplayFor(modelItem => item.CellsForDisplay)
                </pre>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateBy)
            </td>
            <td>
                @Html.ActionLink("Create Active Game", "CreateGame", "UserGame", new { templateId = item.Id }, new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |

                @if (User != null && appUser != null)
                {
                    if (appUser.Id == item.UserId || User.IsInRole(RoleKeys.ADMIN))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    }
                }
            </td>
        </tr>
    }

    @if (Model == null || Model.Templates.Count() <= 0)
    {
        <tr>
            <td colspan="5">
                Sorry but there are no templates to show. Why not create one?!
            </td>
        </tr>
    }
</table>

GameOfLife.Mvc/Views/UserTemplate/UserTemplates.cshtml
@using GameOfLife.Data
@model GameOfLife.Mvc.Models.TemplatesListViewModel

@{
    ViewBag.Title = "My Templates";

    var appUser = User.ToApplicationUser();
}

<h2>Templates</h2>

<p>
    @Html.ActionLink("Create New", "Edit", null, new { @class = "btn btn-primary" })
</p>

@using (Html.BeginForm("SearchMyTemplates", "UserTemplate"))
{
    @Html.EditorFor(m => m.Filter, new { @class = "form-control" })
    <input type="submit" class="btn btn-primary" value="Search" />
    @Html.ActionLink("Clear", "MyTemplates", "UserTemplate", null, new { @class = "btn btn-default" })
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].Width)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Templates[0].Cells)
        </th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model.Templates)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height)
            </td>
            <td>
                <pre style="display:inline-block;">
                    @Html.DisplayFor(modelItem => item.CellsForDisplay)
                </pre>
            </td>
            <td>
                @Html.ActionLink("Create Active Game", "CreateGame", "UserGame", new { templateId = item.Id }, new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |

                @if (User != null && appUser != null)
                {
                    if (appUser.Id == item.UserId || User.IsInRole(RoleKeys.ADMIN))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                        <span>|</span>
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    }
                }
            </td>
        </tr>
    }

    @if (Model == null || Model.Templates.Count() <= 0)
    {
        <tr>
            <td colspan="5">
                Sorry but there are no templates to show. Why not create one?!
            </td>
        </tr>
    }
</table>